DefaultContentLanguage = "it"
baseurl = "https://fundor333.com/"
languageCode = "it"
title = "Fundor 333 ğŸ’»"
theme = "f333-hugo"
disqus_shortname = "fundor333"

[params]
	Author = "Fundor 333"
	disqus_shortname = "fundor333"
	subtitle = "import antigravity"

[[params.social]]
	name="facebook.svg"
	color="#3B5998"
	url="https://www.facebook.com/fundor333"

[[params.social]]
	name="mastodon.svg"
	color="#189efc"
	url="https://mastodon.social/@fundor333"

[[params.social]]
	name="twitter.svg"
	color="#1DA1F2"
    	url="https://twitter.com/fundor333"

[[params.social]]
    name="youtube.svg"
    url="https://www.youtube.com/user/Fundor333"

[[params.social]]
	name="instagram.svg"
	url="https://www.instagram.com/fundor333/"

[[params.social]]
	name="reddit.svg"
	url="https://www.reddit.com/user/fundor333"

[[params.social]]
	name="linkedin.svg"
	color="#0077B5"
    	url="https://it.linkedin.com/in/matteo-scarpa-78969263"

[[params.social]]
	name="github.svg"
	color="#181717"
    	url="https://github.com/fundor333"

[[params.social]]
	name="gitlab.svg"
	color="#E24329"
    	url="https://gitlab.com/fundor333"

[[menu.main]]
	name="ğŸ“ševerything"
[[menu.main]]
    name="ğŸ“šarchive"
    parent="ğŸ“ševerything"
    url="/post/"
[[menu.main]]
	name="ğŸ““blog"
  	url="/categories/blog/"
  	parent="ğŸ“ševerything"
  	text="I miei articoli, ordinati cronologicamente"
[[menu.main]]
	name="ğŸ‘¨â€ğŸ’»dev"
	url="/categories/dev/"
	parent="ğŸ“ševerything"
	text="Il mio diario di sviluppo"

[[menu.main]]
	name="ğŸ”—resources"
  	url="/resources/"
  	text="Link utili che consiglio"
	
[[menu.main]]
	name="ğŸ¤µğŸ»about"
	url="/about/"
	text="Chi sono e cosa faccio"
[[menu.main]]
	name="ğŸ’»project"
	url="/project/"
	text="In sintesi i miei progetti"
[[menu.main]]
	name="ğŸ“Œthe source code"
	url="https://gitlab.com/fundor333/fundor333.gitlab.io"
	text="Il sorgente del sito"
[[menu.main]]
	name="ğŸ“°the feed"
	url="https://fundor333.com/index.xml"
	text="Ultime news del sito"