DefaultContentLanguage = "it"
baseURL = "https://www.fundor333.com/"
disableRSS = false
disqusShortname = "fundor333"
googleAnalytics = "UA-44064318-2"
languageCode = "it-it"
pygmentsUseClassic = true
rssLimit = 10
theme = "f333"
title = "Fundor 333"
pygmentsUseClasses = true
enableRobotsTXT = true
[author]
name = "Fundor 333"
[[menu.main]]
identifier = "ğŸ‰"
name = "hoarding"
url = "/hoarding/"
weight = 4
[[menu.main]]
identifier = "ğŸ“…"
name = "convention"
url = "/event/"
weight = 8
[[menu.main]]
identifier = "ğŸ’¬"
name = "talk"
url = "/talk/"
weight = 7
[[menu.main]]
identifier = "ğŸ‘¨ğŸ»â€ğŸ’»"
name = "about"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "ğŸ“š"
name = "blog"
url = "/post/"
weight = 1
[outputs]
section = ["HTML", "RSS", "Calendar"]
[params]
subtitle = "import antigravity"
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = true
useSessionStorage = true
