baseurl = "https://fundor333.com/"
languageCode = "it"
title = "ğŸ’»Fundor 333"
theme = "f333-hugo"
disqusShortname = "shortcode-here"

[params]
    Author = "Fundor 333"
    disqus_shortname = "fundor333"
    subtitle = "import antigravity"

[[menu.social]]
  name="facebook"
  url="https://www.facebook.com/fundor333"
  identifier="facebook"
[[menu.social]]
    name="twitter"
    url="https://twitter.com/fundor333"
[[menu.social]]
    name="linkedin"
    url="https://it.linkedin.com/in/matteo-scarpa-78969263"
[[menu.social]]
    name="github"
    url="https://github.com/fundor333"
[[menu.social]]
    name="gitlab"
    url="https://gitlab.com/fundor333"
[[menu.social]]
    name="feed"
    url="index.xml"

[[params.main]]
  name="ğŸ““blog"
  url="/categories/blog/"
  text="I miei articoli, ordinati cronologicamente"
[[params.main]]
  name="ğŸ“ševerything"
  url="/post/"
  text="Tutti gli articoli del mio blog"
[[params.main]]
  name="ğŸ”—resources"
  url="/resources/"
  text="Link utili che consiglio"
[[params.main]]
  name="ï¸âŒ¨ï¸dev"
  url="/categories/dev/"
  text="Il mio diario di sviluppo"
[[params.main]]
  name="ğŸ¤µğŸ»about"
  url="/about/"
  text="Chi sono e cosa faccio"
[[params.main]]
  name="ğŸ’»project"
  url="/project/"
  text="In sintesi i miei progetti"
[[params.main]]
  name="ğŸ“Œthe source"
  url="https://github.com/fundor333/fundor333.github.io"
  text="Il sorgente del sito"
